services:
  devhabit.api:
    image: ${DOCKER_REGISTRY-}devhabitapi
    build:
      context: .
      dockerfile: DevHabit.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    depends_on:
      devhabit.postgres:
        condition: service_healthy

  devhabit.postgres:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devhabit
    volumes:
      - ./.containters/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres", "-d", "devhabit"]
        interval: 10s
        timeout: 5s
        retries: 5

  devhabit.seq:
    image: datalust/seq:latest
    environment:
        ACCEPT_EULA: "Y"
    volumes:
        - ./.containters/seq_data:/data
    ports:
        - 8080:80
        - 5341:5341
  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
        DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
        - 18888:18888